- OracleLinux/6/README.md
- OracleLinux/6/Vagrantfile
- OracleLinux/6/scripts/install.sh
- OracleLinux/7/README.md
- OracleLinux/7/Vagrantfile
- OracleLinux/7/scripts/install.sh
Added two plugins "vagrant-reload" and "vagrant-proxyconf" to both OL 6 and OL 7.
While proxyconf automatically manages the proxy configuration for Vagrant and VM, "reload" is required to get the VM rebooted once the updated kernel (and user-space stuff) has been installed during the provisioning process.
> Added reload and proxyconf to OL6/7

- DockerEngine/Vagrantfile
- Kubernetes/Vagrantfile
- OracleDatabase/11.2.0.2/Vagrantfile
- OracleDatabase/12.2.0.1/Vagrantfile
- OracleLinux/6/Vagrantfile
- OracleLinux/7/Vagrantfile
`config.vm.box` is used by vagrant to resolve the box file in the local cache. I.e if you use a different name, Vagrant will re-download the same box file again unnecessarily bloating the local cache.
The reason for dropping the "-box" is because of information redundancy. `config.vm.box` already makes it clear that it is a box.
> Consistent box name, used by vagrant for caching

- DockerEngine/scripts/install.sh
I like to have `vagrant` user part of the `docker` group, so you don't have to `sudo` every time.
> RFC: Add vagrant to docker group

- Kubernetes/README.md
- Kubernetes/Vagrantfile
- Kubernetes/scripts/provision.sh
With `USE_PREVIEW` script parameter the user can decide to install the latest tech preview or the latest stable version.
Default value is `true` (consistent with current version)
> Kubernetes: add USE_PREVIEW parameter

- Kubernetes/README.md
- Kubernetes/Vagrantfile
- Kubernetes/scripts/kubeadm-setup-master.sh
- Kubernetes/scripts/kubeadm-setup-worker.sh
- Kubernetes/scripts/provision.sh
Add support for [Oracle Container Registry Mirror](https://docs.oracle.com/cd/E52668_01/E88884/html/requirements-registry-mirror.html) and [Local Registry](https://docs.oracle.com/cd/E52668_01/E88884/html/requirements-registry-local.html).  
Using a Registry Mirror in your region or a Local Registry improves provisioning speed.
> Kuberentes; add support for Registry Mirrors / Local Registries

- OracleLinux/preview/scripts/install.sh
under public-yum-ol7.repo "Preview" channel was already there.
So I've removed it from "install.sh".
> fixed yum preview repos

- LAMP/scripts/lamp.sh
no need to add yum repo for MySQL8 (it's part of OL7.5 updated image)
fixed MySQL releases mentioned within different files
> Updated MySQL Community Release to 8.0 #2

- OracleLinux/preview/scripts/install.sh
As in subject, the script has to look for an entry that starts with "4.14" and not look for "4.14" in the entire row.
> fixed uek5 grep - look for string starting with 4.14

- OracleLinux/preview/scripts/install.sh
previous version manually install VBOx guest-additions for UEK5.
Now we have  pre-built kmod RPM public-available so I've applied this change.
> added kmod-vboxguest-uek5 RPM instead of manual install

- DockerEngine/Vagrantfile
- LAMP/Vagrantfile
- OracleDatabase/11.2.0.2/Vagrantfile
- OracleDatabase/12.2.0.1/Vagrantfile
- OracleLinux/preview/Vagrantfile
This addresses the enhancement in issue #39.
The resolution for issue #31 added `config.vm.define NAME` to the Vagrantfiles for the OracleLinux 6 and OracleLinux 7 boxes, so that Vagrant identifies the VM using the NAME variable, instead of "default", during vagrant up/suspend/halt/destroy/status operations.  This pull request adds the same to the remaining boxes (except for the Kubernetes box, which is already compliant, per @AmedeeBulle).
To validate, `cd` to the directory with the Vagrantfile and run `vagrant status`.  It isn't necessary to actually create the box.  Vagrant should identify the boxes as follows:
- DockerEngine:  "ol7-docker-engine"
- LAMP:  "ol7-lamp"
- OracleDatabase 11.2.0.2:  "oracle11g-xe-vagrant"
- OracleDatabase 12.2.0.1:  "oracle-12201-vagrant"
- OracleLinux …
> Set name for all vagrant images (#39)

- Kubernetes/Vagrantfile
When `vagrant-proxyconf` plugin is installed, we will push the host HTTP proxy to the guest boxes.
> Import local proxy configuration if available

- ContainerRegistry/README.md
- ContainerRegistry/Vagrantfile
- ContainerRegistry/scripts/kubeadm-setup-registry.sh
- ContainerRegistry/scripts/provision.sh
- Kubernetes/README.md
This is a new simple Vagrantfile providing a local Container Registry
It is mainly a companion Box for the Kubernetes Vagrantfile to allow local caching of the Kubernetes containers, but it can be used for any other purpose.
> New Vagrantfile: local Container Registry

- ContainerRegistry/Vagrantfile
- ContainerRegistry/scripts/provision-cr.sh
- ContainerRegistry/scripts/provision.sh
Fix an issue in the  ContainerRegistry setup: when proxies are used, Docker proxies need to be configured after docker is installed and before the Registry image is pulled.
> ContainerRegistry: enable Docker proxies during provisioning

- OracleDatabase/11.2.0.2/scripts/install.sh
This fixes issue #50.
This pull request adds one line to the Oracle Database 11.2.0.2 box `install.sh` script to grant write permissions on the Oracle XE installer directory (`/vagrant/Disk1`) before removing it.
To validate, `cd` to the OracleDatabase/11.2.0.2 directory, and run `vagrant up`. After the VM is created, Oracle XE should be installed correctly, and the directory `/vagrant/Disk1` should not exist.
> Remove Database 11.2.0.2 box installer directory (#50)

- ContainerRegistry/.env
- ContainerRegistry/.gitignore
- ContainerRegistry/README.md
- ContainerRegistry/Vagrantfile
- Kubernetes/.env
- Kubernetes/.gitignore
- Kubernetes/README.md
- Kubernetes/Vagrantfile
This PR enables usage of `.env` files for configuration (instead of editing the Vagrantfile).  
It relies the [vagrant-env](https://github.com/gosuri/vagrant-env) plugin.
The plugin is optional, users can still edit the Vagrantfile as before. If the plugin is installed `.env` files are considered and take precedence over the Vagrantfile.
It is recommended to make changes in `.env.local` as this file is not versioned.
Users of the [vagrant-proxyconf](https://github.com/tmatilai/vagrant-proxyconf) plugin can also use the `.env` files to store HTTP proxy configuration.
As side-effect of this change, environment variables can also be used to configure boxes. They take precedence over any other methods.
>  Kubernetes/ContainerRegistry: use .env files for configuration 

- Kubernetes/.env
- Kubernetes/Vagrantfile
Change defaults to use the supported channels.
(Developer channel requires additional changes and won't work out of the box)
> K8s - Use supported channel by default

- ContainerRegistry/scripts/kubeadm-setup-registry.sh
- Kubernetes/.env
- Kubernetes/README.md
- Kubernetes/Vagrantfile
- Kubernetes/scripts/provision.sh
Some refactoring to support the 1.1.10 developer release.
We still install the latest supported release by default (1.1.9), but one can now install 1.1.10 by setting
```ruby
USE_DEV = true
KUBE_PREFIX = "/kubernetes_developer"
```
> K8s: refactor for k8s 1.1.10

- ContainerRegistry/.gitattributes
- Kubernetes/.gitattributes
Disable automatic file conversion to DOS type for shell scripts.
Git for windows will automatically convert `lf` to `crlf` when the `core.autocrlf` configuration parameter is set to `true`.
This PR forces unix line termination for shell scripts (`.sh` files)
Addresses #68
> Don't convert end-of-line for shell scripts

- OracleDatabase/11.2.0.2/README.md
- OracleDatabase/11.2.0.2/Vagrantfile
- OracleDatabase/11.2.0.2/scripts/install.sh
- OracleDatabase/12.2.0.1/README.md
- OracleDatabase/12.2.0.1/Vagrantfile
- OracleDatabase/12.2.0.1/scripts/install.sh
- OracleDatabase/18.3.0/README.md
- OracleDatabase/18.3.0/Vagrantfile
- OracleDatabase/18.3.0/scripts/install.sh
This implements the enhancement in Issue #33. By default, the VM time zone is set to the host time zone when the host time zone is an integer hour offset from GMT. When the host time zone is **not** an integer hour offset (e.g., in India), the VM time zone is set to UTC. In either case, a different time zone can be specified either by name (e.g., "America/Los_Angeles") or by an offset from GMT (e.g., "Etc/GMT-2") in the environment section of the `Vagrantfile`.
Changes are:
- In the `Vagrantfile`, add code to determine host time zone. If the host time zone isn't an integer hour offset from GMT, then default to UTC.
- In the `Vagrantfile`, add a variable in the environment section to pass the time zone to `install.sh`
- In `install.sh`, add code to set the VM's time zone using the …
> Allow configuration of Database 12.2.0.1 box time zone (#33)

- OracleDatabase/11.2.0.2/.gitattributes
- OracleDatabase/12.2.0.1/.gitattributes
- OracleDatabase/18.3.0/.gitattributes
This addresses Issue #71. By default, Git for Windows converts Unix line endings (LF) to DOS line endings (CR/LF). This causes the `setPassword.sh` scripts for the 3 Oracle Database boxes to fail when run in the guest.
This PR adds the same `.gitattributes` file that @AmedeeBulle created for the ContainerRegistry and Kubernetes boxes to the 11.2.0.2, 12.2.0.1 and 18.3.0 database boxes. The `.gitattributes` file tells Git to use Unix line endings for `.sh` files. With Unix line endings, the `setPassword.sh` scripts run correctly.
> Prevent EOL conversion for .sh scripts for DB boxes (#71)

- OracleDatabase/11.2.0.2/README.md
- OracleDatabase/11.2.0.2/scripts/install.sh
- OracleDatabase/11.2.0.2/userscripts/.gitignore
- OracleDatabase/11.2.0.2/userscripts/put_custom_scripts_here.txt
- OracleDatabase/12.2.0.1/README.md
- OracleDatabase/12.2.0.1/scripts/install.sh
- OracleDatabase/12.2.0.1/userscripts/.gitignore
- OracleDatabase/12.2.0.1/userscripts/put_custom_scripts_here.txt
- OracleDatabase/18.3.0/README.md
- OracleDatabase/18.3.0/scripts/install.sh
- OracleDatabase/18.3.0/userscripts/.gitignore
- OracleDatabase/18.3.0/userscripts/put_custom_scripts_here.txt
- OracleDatabase/18.4.0-XE/README.md
- OracleDatabase/18.4.0-XE/scripts/install.sh
- OracleDatabase/18.4.0-XE/userscripts/.gitignore
- OracleDatabase/18.4.0-XE/userscripts/put_custom_scripts_here.txt
This adds functionality to the 4 Oracle Database boxes to give users the option of running user-defined shell and/or SQL scripts after the database is set up and started. It addresses the enhancement in Issue #85. The functionality is very similar to what's used in the [docker-images](https://github.com/oracle/docker-images) repository.
The following changes are implemented in each of the 4 database boxes (11.2.0.2, 12.2.0.1, 18.3.0, and 18.4.0-XE):
* Add a directory called `userscripts` to contain user-defined scripts.
* Add a file called `put_custom_scripts_here.txt` in the `userscripts` directory. This file contains usage instructions.
* Add a `.gitignore` file in the `userscripts` directory that ignores all files except `put_custom_scripts_here.txt` and `.gitignore` itself.
* Add code …
> Allow running user-defined post-setup scripts (#85)

- OracleDatabase/18.4.0-XE/Vagrantfile
For the Oracle Database 18c XE box, the hostname must be "localhost", or listener configuration will fail. Since "localhost" is the default hostname, the `config.vm.name = NAME` line was originally commented out in the `Vagrantfile`. However, if another Vagrantfile that specifies a hostname is merged with this box's Vagrantfile, the box may end up using that hostname instead of "localhost". (See [https://www.vagrantup.com/docs/vagrantfile/#load-order-and-merging](https://www.vagrantup.com/docs/vagrantfile/#load-order-and-merging).) This seems to be what happened in Issue #91.
This change explicitly sets the hostname for the Oracle Database 18c XE box to "localhost" in the `Vagrantfile`, to reduce the chance of it being overridden by a hostname specified in another Vagrantfile. …
> Explicitly set 18c XE box hostname (#91)

- Kubernetes/Vagrantfile
Changes to support Kubernetes 1.12 (Oracle Container Services for use with Kubernetes 1.1.12)
> K8s: update for 1.12 release

- Kubernetes/Vagrantfile
Address issue #100, the release of K8s 1.12 breaks the `MANAGE_FROM_HOST` feature.
Ultimately `kubeadm-setup.sh` should handle options properly...
> K8s: fix 1.12 regression

- OracleDatabase/11.2.0.2/README.md
- OracleDatabase/11.2.0.2/userscripts/put_custom_scripts_here.txt
- OracleDatabase/12.1.0.2/README.md
- OracleDatabase/12.1.0.2/userscripts/put_custom_scripts_here.txt
- OracleDatabase/12.2.0.1/README.md
- OracleDatabase/12.2.0.1/userscripts/put_custom_scripts_here.txt
- OracleDatabase/18.3.0/README.md
- OracleDatabase/18.3.0/userscripts/put_custom_scripts_here.txt
- OracleDatabase/18.4.0-XE/README.md
- OracleDatabase/18.4.0-XE/userscripts/put_custom_scripts_here.txt
This addresses Issue #99. It corrects the instructions in the `README.md` and `userscripts/put_custom_scripts_here.txt` files for all 5 Oracle Database boxes to state that user-defined post-setup shell scripts are run as root, rather than vagrant.
> Correct DB box post-setup script instructions (#99)

- ContainerRegistry/.gitignore
- Kubernetes/.env
- Kubernetes/Vagrantfile
- Kubernetes/scripts/kubeadm-setup-master.sh
- Kubernetes/scripts/provision.sh
**Do not merge this until K8s 1.12.6 is released!**
Background: the `kubeadm-setup.sh` in 1.12.5 script does not properly handle `--apiserver-advertise-address` and `--apiserver-cert-extra-sans` parameters. Our Vagrant setup therefore _patches_ the script as workaround. This issue has been solved (OLCNE-164) and the fix is in 1.12.6 which will be released shortly. We need to update the Vagrant setup accordingly as the workaround won't work anymore when 1.12.6 gets released.
Additionally this PR adds configuration variables to allow installation from local yum repository and to pin Docker or Kubernetes version.
> Support for K8s 1.12.6

- OracleDatabase/18.4.0-XE/scripts/install.sh
This addresses the enhancement in Issue #104 by adding code to `install.sh` to:
* give read permissions on the `tnsnames.ora` file to all OS users
* add an entry to the `tnsnames.ora` file for the PDB
These changes allow the vagrant user to connect to both the CDB and the PDB using TNS.
To validate:
* run `vagrant up`
* ssh to the box
* run `. oraenv` and enter "XE" for the ORACLE_SID
* verify that both `sqlplus system/<password>@XE` and `sqlplus system/<password>@XEPDB1` successfully connect to the database
> Improve tnsnames.ora usability for 18c XE (#104)

- Kubernetes/Vagrantfile
Allow empty `KUBE_PREFIX`.
(Useful to test against local registry where containers have no prefix)
> K8s: allow empty registry prefix

- OracleAPEX/scripts/ords.sh
This change allows the ORDS service to be started on bootup. It includes a system logger to be able to query the ords unit via journalctl.
Signed-off-by: Jerson Zúñiga-Coayla jzunigacoayla@gmail.com
> Launch ORDS as a systemd service. Fixes #133

- Kubernetes/.env
- Kubernetes/README.md
- Kubernetes/Vagrantfile
Changes in the K8s boxes as login is no longer needed for the K8s repo.
> Kubernetes: OCR no longer requires docker login for open source projects

- OracleAPEX/scripts/apex.sh
Create APEX tablespace datafile in PDB's datafile directory (`$ORACLE_BASE/oradata/$ORACLE_SID/$ORACLE_PDB`), instead of CDB's datafile directory (`$ORACLE_BASE/oradata/$ORACLE_SID`).
To validate, build the box and verify that:
- The file `apex01.dbf` is created in the directory `/opt/oracle/oradata/XE/XEPDB1`.
- Logins to APEX work normally.
> Fix APEX tablespace directory (#163)

- OLCNE/scripts/provision.sh
When Vagrant runs on OCI, yum tries to determine the OCI Region to use the best yum mirror.
This requires `jq`which is installed by default on cloud images but not on the `ol7` vagrant base box.
> OLCNE: Install jq (OCI requirement)

- OracleDatabase/11.2.0.2/README.md
- OracleDatabase/12.2.0.1/README.md
- OracleLinux/6/README.md
Fixes #174 by
* Updating `OracleLinux/6/README.md` to refer to Oracle Linux 6, instead of Oracle Linux 7
* Updating `OracleDatabase/11.2.0.2/README.md` and `OracleDatabase/12.2.0.1/README.md` to refer to Oracle Linux 7, instead of Oracle Linux 7.3
> Update Oracle Linux versions in READMEs (#174)

- OracleDatabase/18.3.0/scripts/install.sh
This is a fix for #179 
@PaulNeumann, I decided rather than switching off and on again the error handling (`set +e` and `set -e`) to handle the error directly in an inline script. That way a `set -e` may not be forgotten or overlooked in the future when something else is added but the change stays atomic and consistent with the runInstaller command itself.
Would you mind testing this on your end as well?
It works fine on my machine but that's a famous quote that I never want to have my name next to it ;)
> Don't abort install on non-zero return code from runInstaller

- OracleDatabase/11.2.0.2/scripts/install.sh
- OracleDatabase/12.1.0.2/scripts/install.sh
- OracleDatabase/12.2.0.1/scripts/install.sh
- OracleDatabase/18.3.0/scripts/install.sh
- OracleDatabase/18.4.0-XE/scripts/install.sh
- OracleDatabase/19.3.0/scripts/install.sh
This fixes #196 by removing the AND (`&&`) lists from the `install.sh` scripts for all 6 of the single-instance database boxes.
To validate, verify that all of the single-instance database boxes build and run correctly.
> Remove AND lists from DB box install scripts

- boxes/oraclelinux-6.json
- boxes/oraclelinux-7.json
- boxes/oraclelinux-8.json
- index.html
This PR adds metadata for the Oracle Linux boxes in GitHub pages (`gh-pages` branch).
> GitHub pages: add boxes metadata

- CODEOWNERS
- OLCNE/.env
- OLCNE/README.md
- OLCNE/Vagrantfile
- OLCNE/scripts/provision.sh
This is an initial commit of an update to the OLCNE Vagrant build to support the as-yet-unreleased Oracle Linux Cloud Native Environment 1.1.0 release, including optional deployment of the new Helm and Istio modules.
Things to note:
* `scripts/provision.sh` has had significant changes to conform to ShellCheck.net rules.
* Masquerading is now disabled for OLCNE
* An operator node is mandatory for multi-master deployments (to workaround OLCNE-1028)
* Helm is automatically deployed if Istio is enabled
This is still WIP because the Istio module doesn't always deploy correctly but I'm having a tough time working out why (it may be a resource issue). Also, because 1.1.0 hasn't actually been released yet, it's impossible to test if you don't have insider access to the release bits.
For now, I'd …
> Updating OLCNE Vagrant build to support 1.1.0 with Helm and Istio

- OLCNE/scripts/provision.sh
At deployment time, a common ssh key is generated in the `/vagrant` shared folder to enable password-less ssh communication between nodes.
On Windows hosts the file looses its permission which needs to be re-set.
> Set permissions on the ssh key

- OracleAPEX/scripts/apex.sh
Fixes #223 by updating the `apex.sh` script to support the APEX 20.1 installer, as well as earlier/later versions. Also eliminates two ShellCheck warnings.
To validate, verify that the box builds and runs correctly with the APEX 20.1 installer, and that the `apex.sh` script exits if the APEX installer is not present.
> APEX box - support APEX 20.1 (#223)

- DockerEngine/scripts/install.sh
This allows the `docker` group to write files in `/etc/docker` which is required for things like `docker login`. I also removed permissions from everyone so users must be members of the group for this access.
> Broaden permissions on /etc/docker

- ContainerRegistry/Vagrantfile
- ContainerRegistry/scripts/provision.sh
- DockerEngine/Vagrantfile
- DockerEngine/scripts/install.sh
- LAMP/Vagrantfile
- OLCNE/Vagrantfile
- OracleDatabase/19.3.0/Vagrantfile
- OracleLinux/6/Vagrantfile
- OracleLinux/7/Vagrantfile
- OracleLinux/8/Vagrantfile
Add support for the `libvirt` provider for the following boxes:
- OracleLinux: all boxes
- LAMP
- DockerEngine
- ContainerRegistry
- OLCNE
- OracleDatabase/19.3.0
(The above changes have been tested)
> Add support for libvirt provider

- OracleAPEX/README.md
- OracleAPEX/Vagrantfile
- OracleAPEX/scripts/database.sh
Adds support for libvirt/KVM to the OracleAPEX project.
- `Vagrantfile`: add libvirt configuration
- `Vagrantfile`: set VM hostname to "localhost"
- `database.sh`: remove code that temporarily modifies `/etc/hosts`
- `README.md`: updates for new functionality and new repo name
- `README.md`: resolve markdownlint warnings
Setting the VM hostname to "localhost" in the `Vagrantfile` and removing the code in `database.sh` that temporarily modifies `/etc/hosts` are required for listener configuration to succeed on libvirt. These changes are consistent with the OracleDatabase/18.4.0-XE project.
This has been tested on both VirtualBox and libvirt/KVM.
> APEX project - add libvirt provider support

- OracleDatabase/18.3.0/.env
- OracleDatabase/18.3.0/README.md
- OracleDatabase/18.3.0/Vagrantfile
- OracleDatabase/19.3.0/.env
- OracleDatabase/19.3.0/README.md
- OracleDatabase/19.3.0/Vagrantfile
Increase default VM memory from 2048 MB to 2300 MB for the OracleDatabase/18.3.0 and OracleDatabase/19.3.0 single-instance database projects to eliminate a memory warning from DBCA. Fixes #241.
The 19.3.0 changes have been tested on both VirtualBox and libvirt. The 18.3.0 changes have been tested on VirtualBox. (18.3.0 doesn't support libvirt yet, but I'm working on that.)
> Increase default VM memory for 18c and 19c boxes (#241)

- CODEOWNERS
- ContainerTools/LICENSE
- ContainerTools/README.md
- ContainerTools/Vagrantfile
- ContainerTools/scripts/install.sh
Introduce a simple Vagrantfile based on the Oracle Linux 8 box with the `container-tools` installed.
> Simple Vagrantfile for the OL8 container-tools module

- OracleDatabase/11.2.0.2/README.md
- OracleDatabase/11.2.0.2/Vagrantfile
- OracleDatabase/12.1.0.2/README.md
- OracleDatabase/12.1.0.2/Vagrantfile
- OracleDatabase/12.2.0.1/README.md
- OracleDatabase/12.2.0.1/Vagrantfile
- OracleDatabase/18.3.0/README.md
- OracleDatabase/18.3.0/Vagrantfile
- OracleDatabase/18.4.0-XE/README.md
- OracleDatabase/18.4.0-XE/Vagrantfile
- OracleDatabase/19.3.0/README.md
- OracleDatabase/19.3.0/Vagrantfile
- OracleDatabase/README.md
Adds support for libvirt/KVM to the single-instance database projects.
- `Vagrantfile`s: add libvirt configuration (except for 19.3.0, which already had it)
- `README.md` files: updates for new functionality
- `OracleDatabase/README.md`: updates for new functionality and repo name; resolve markdownlint warnings
These changes have been tested on both VirtualBox and libvirt/KVM.
> Database projects - add libvirt support

- OracleDatabase/11.2.0.2/README.md
- OracleDatabase/11.2.0.2/Vagrantfile
- OracleDatabase/12.1.0.2/README.md
- OracleDatabase/12.1.0.2/Vagrantfile
- OracleDatabase/12.2.0.1/README.md
- OracleDatabase/12.2.0.1/Vagrantfile
- OracleDatabase/18.3.0/README.md
- OracleDatabase/18.3.0/Vagrantfile
- OracleDatabase/18.4.0-XE/README.md
- OracleDatabase/18.4.0-XE/Vagrantfile
- OracleDatabase/19.3.0/README.md
- OracleDatabase/19.3.0/Vagrantfile
Don't install plugins in the `Vagrantfile`s for the single-instance database projects. Changes for each project are:
`Vagrantfile`:
- Removed code that installs the vagrant-proxyconf plugin
- Updated proxy configuration code to the latest version developed by @AmedeeBulle (see #265). This handles both upper- and lower-case proxy environment variables and doesn't set `no_proxy` unless a proxy has been defined.
`README.md`:
- Added "Optional plugins" section consistent with other projects in this repo
This has been tested on both VirtualBox and libvirt/KVM.
(I still owe you a PR with these changes for the APEX project. I didn't include the APEX project here to avoid any conflicts with #271.)
Signed-off-by: Paul Neumann …
> Database projects - Don't install plugins

- OracleAPEX/scripts/database.sh
Change hostname from "oracle-18c-apex" to "localhost" in the section of `database.sh` that creates the tnsnames.ora entry for the PDB. This is consistent with `OracleDatabase/18.4.0-XE/scripts/install.sh`. Fixes #274.
To validate:
- Build the project
- `vagrant ssh`
- Run `. oraenv`, using "XE" for the ORACLE_SID
- Verify that `sqlplus pdbadmin/\"<password>\"@XEPDB1` successfully connects
Again, I apologize for missing this.
> APEX project - Fix tnsnames entry for PDB

- OracleAPEX/README.md
- OracleAPEX/Vagrantfile
Don't install plugins in the `Vagrantfile` for the APEX project. Changes are:
`Vagrantfile`:
- Removed code that installs the vagrant-reload and vagrant-proxyconf plugins. (The vagrant-reload plugin wasn't actually used.)
- Updated proxy configuration code to the latest version developed by @AmedeeBulle (see #265). This handles both upper- and lower-case proxy environment variables and doesn't set `no_proxy` unless a proxy has been defined.
- Updated comment for provider-specific configuration.
`README.md`:
- Fixed typo.
- Added "Optional plugins" section consistent with other projects in this repo.
This has been tested on both VirtualBox and libvirt/KVM.
> APEX project - Don't install plugins

- OracleAPEX/scripts/ords.sh
Fixes #281 by updating the `ords.sh` script to support the ORDS 20.2 installer, as well as earlier/later versions. Also eliminates two ShellCheck warnings.
To validate, verify that the project builds and runs correctly with the ORDS 20.2 installer, and that the `ords.sh` script exits if the ORDS installer is not present.
> APEX project - Support ORDS 20.2 (#281)

- OLCNE/Vagrantfile
- OLCNE/scripts/provision.sh
NGINX image is not pulled when proxies are used.
This PR pulls the image beforehand to make it available to OLCNE agent.
> OLCNE: pull NGINX image pro-actively on master nodes

- OracleLinux/7/README.md
- OracleLinux/7/Vagrantfile
- OracleLinux/8/README.md
- OracleLinux/8/Vagrantfile
Small enhancement to the OracleLinux/7 and 8 projects to support parameters for the extensions.
--
> Pass environment variables to extensions

- DockerEngine/Vagrantfile
- Kubernetes/Vagrantfile
As we plan to drop the extra disk from the VirtualBox boxes (see #278), add disk creation for the projects using it.
The Vagrant _disks_ feature is still experimental, but works well for our use case. This has been tested by stripping the extra disk from our latest VirtualBox boxes.
Tagged as WIP for review and until we ship new boxes without the extra disk.
Only for the virtualbox provider (libvirt already have such feature).
Note that disk names must be unique due to hashicorp/vagrant#11755.
> Use Vagrant "disks" feature to add extra disk.

- OracleDG/scripts/setup.sh
- OracleFPP/scripts/setup.sh
- OracleRAC/scripts/setup.sh
**Reference:**
Issue: https://github.com/oracle/vagrant-projects/issues/308
**Fix Details:**
Change environment variable export commands for variable `DOMAIN_NAME` in **setup.sh** for consistency and to fix bug with DG creations.
**Variable Use Validation:**
- To verify issue prior to fix being implemented: `grep -r DOMAIN * |grep -v NAME`  <--- Shows that variable passed into **setup.sh** is just named **DOMAIN**
- To verify variable refence in setup.sh: `grep -r "export\ DOMAIN" *`  <--- Shows that variable is used inconsistently prior to fix
**Test Details:**
- Tested fixed **setup.sh** with new VirtualBox based DG environment creation.
> ISSUE-308: Fix inconsistency in variable definitions in setup.sh

- OLCNE/Vagrantfile
Latest boxes are based on OL7 Update 9 which come with UEK6 kernel.
As OLCNE is not certified yet against UEK6 this PR ensures the project uses the latest box with UEK5.
--
> OLCNE: use box with UEK5

- OLCNE/README.md
To make it very clear that you need to use `localhost` or `127.0.0.1` in the URL and enable `BIND_PROXY`.
Resolves #324.
> Add more docs on accessing Kubernetes Dashboard

- OLCNE/Vagrantfile
OLCNE 1.1.7 supports UEK6, so the restriction is no longer required.
> Remove restriction on OL7 box version 

- OLCNE/README.md
Correct link to `CONTRIBUTING.md` in OLCNE `README.md` file. Fixes #329.
> Correct link in OLCNE README.md

- boxes/oraclelinux/6.json
- boxes/oraclelinux/7.json
- boxes/oraclelinux/8.json
Republish images, covering following advisories:
OL6:
- ELSA-2019-1652 libssh2 security update
- ELSA-2019-1726 dbus security update
- ELSA-2019-1774 vim security update
- ELSA-2019-2471 openssl security update
- ELSA-2019-4152 nss-softokn security update
- ELSA-2019-4877 python security update
- ELSA-2020-4182 kernel security and bug fix update
- ELSA-2020-5561 curl security update
- ELSA-2021-9019 sudo security update
OL7:
- ELSA-2020-5566-1 openssl security update
- ELSA-2021-0221 sudo security update
- ELSA-2021-0336 kernel security, bug fix, and enhancement update
- ELSA-2021-0348 glibc security and bug fix update
- ELSA-2021-9006 Unbreakable Enterprise kernel security update
OL8:
- ELSA-2020-5476 openssl security and bug fix update
- ELSA-2020-5483 gnutls security and bug fix update …
> Metadata for updated Vagrant Boxes

- OLCNE/scripts/provision.sh
Found that current OLCNE environment is not deploying in vagrant, it fails with below error:
```
$ vagrant up
```
Added passing of:
```
--restrict-service-externalip-ca-cert
--restrict-service-externalip-tls-cert
--restrict-service-externalip-tls-key
```
for each `olcnectl module create --module kubernetes` invocation.
Result:
```
Signed-off-by: Denis Obada <denis.o@linux.com>
```
> OLCNE deployment fixes

- OLCNE/Vagrantfile
A bit late to the 🎉 , I think that one slipped through the net...
`EXTRA_DISK` should be false by default
--
> OLCNE: defaults EXTRA_DISK to false

- OracleDatabase/18.4.0-XE/.env
- OracleDatabase/18.4.0-XE/README.md
- OracleDatabase/18.4.0-XE/Vagrantfile
- OracleDatabase/18.4.0-XE/scripts/install.sh
Add an option to the OracleDatabase/18.4.0-XE project to save the database installer file. Changes are:
`.env`
- Add a Boolean configuration parameter called "VM_KEEP_DB_INSTALLER" (default false).
`README.md`
- Document the "VM_KEEP_DB_INSTALLER" parameter in the Configuration section.
`Vagrantfile`
- Add code to evaluate the "VM_KEEP_DB_INSTALLER" parameter and pass it to `install.sh`.
`scripts/install.sh`
- Ensure wget is installed (it's already installed in the current oraclelinux/7 box, but just in case).
- Download the database installer file to `/vagrant`, if it's not already present.
- Install the database software from `/vagrant`, instead of directly from OTN.
- Delete the database installer file if the "KEEP_DB_INSTALLER" environment variable is false.
Closes #279.
To validate: …
> 18.4.0-XE - Add save installer option

- OLCNE/scripts/provision.sh
Updated `mkdir` call for `/root/.ssh` to not complain when the directory already exists, an annoying error which appears during re-running of provisioning steps.
```
Signed-off-by: Denis Obada <denis.o@linux.com>
```
> Handling of existing /root/.ssh

- ContainerTools/README.md
- DockerEngine/README.md
- LAMP/README.md
Add notes to the `README.md` files for the ContainerTools, DockerEngine and LAMP projects to state that the projects are deprecated and provide links to the appropriate OracleLinux project. See the comments on #358 for background.
> Update deprecated project READMEs

- CODEOWNERS
Due to internal role changes, the new owner of the OLCNE project
should now be @rafabene. 
> [update] Update OLCNE code owner to rafabene

- OLCNE/scripts/provision.sh
Without this option, flannel will use eth0 which does not provide
inter-vm connectivity.
Fixes #365
> fix(olcne): specify network data plane interface.

- boxes/oraclelinux/7-btrfs.json
- boxes/oraclelinux/7.json
- boxes/oraclelinux/8-btrfs.json
- boxes/oraclelinux/8.json
Metadata for latest boxes:
- Oracle Linux 8 Update 4 with UEK6 Update 2
- Oracle Linux 7 Update 9 with UEK6 Update 2
Also add a new flavor for the boxes: root filesystem on btrfs instead of xfs on lvm.
Boxes are named `oraclelinux/7-btrfs` and `oraclelinux/8-btrfs`.
--
> build(metadata):  metadata for latest boxes / new btrfs boxes

- OracleDatabase/12.1.0.2/scripts/install.sh
- OracleDatabase/12.2.0.1/scripts/install.sh
- OracleDatabase/18.3.0/scripts/install.sh
- OracleDatabase/19.3.0/scripts/install.sh
Modify the `install.sh` command that updates `/etc/oratab` for the OracleDatabase/12.1.0.2, OracleDatabase/12.2.0.1, OracleDatabase/18.3.0, and OracleDatabase/19.3.0 projects to ensure that it changes the correct "N" character. Fixes #370.
To test, configure the installation to use a SID name and/or an ORACLE_HOME directory name containing an "N" character. Build the VM, and verify that only the last "N" character on the last line of `/etc/oratab` has been changed to "Y".
> DB projects - Correct install.sh for oratab

- OracleDatabase/21.3.0/.env
- OracleDatabase/21.3.0/.gitattributes
- OracleDatabase/21.3.0/.gitignore
- OracleDatabase/21.3.0/README.md
- OracleDatabase/21.3.0/Vagrantfile
- OracleDatabase/21.3.0/ora-response/db_install.rsp.tmpl
- OracleDatabase/21.3.0/ora-response/dbca.rsp.tmpl
- OracleDatabase/21.3.0/scripts/install.sh
- OracleDatabase/21.3.0/scripts/oracle-rdbms.service
- OracleDatabase/21.3.0/scripts/setPassword.sh
- OracleDatabase/21.3.0/userscripts/.gitignore
- OracleDatabase/21.3.0/userscripts/put_custom_scripts_here.txt
Adds an OracleDatabase/21.3.0 project, based on the OracleDatabase/19.3.0 project.
Notable changes from the 19.3.0 project:
- Use Oracle Linux 8 instead of Oracle Linux 7
- Increase default VM memory to 2.5 GB to avoid DBCA warning
- Move oraInventory out of the ORACLE_BASE directory, as recommended in the documentation
- 21c Oracle homes are read-only by default, so create network configuration files in ORACLE_BASE_HOME/network/admin, instead of ORACLE_HOME/network/admin
- install.sh script:
- Address all ShellCheck warnings
- Remove unnecessary use of sudo (script runs as root)
- Use /tmp for db_install and dbca response files. This ensures that the response files aren't left under /vagrant if an error occurs.
- Ensure that permissions on setPassword.sh are set correctly
- Minor …
> Add OracleDatabase/21.3.0 project

- OracleDatabase/21.3.0-XE/.env
- OracleDatabase/21.3.0-XE/.gitattributes
- OracleDatabase/21.3.0-XE/.gitignore
- OracleDatabase/21.3.0-XE/README.md
- OracleDatabase/21.3.0-XE/Vagrantfile
- OracleDatabase/21.3.0-XE/ora-response/oracle-xe-21c.conf.tmpl
- OracleDatabase/21.3.0-XE/scripts/install.sh
- OracleDatabase/21.3.0-XE/scripts/setPassword.sh
- OracleDatabase/21.3.0-XE/userscripts/.gitignore
- OracleDatabase/21.3.0-XE/userscripts/put_custom_scripts_here.txt
Adds an OracleDatabase/21.3.0-XE project, based on the OracleDatabase/18.4.0-XE project.
Notable changes from the 18.4.0-XE project:
- Use Oracle Linux 8 instead of Oracle Linux 7
- Increase default VM memory to 2300 MB (approximately 2.25 GB) to avoid memory warning during installation
- 21c Oracle homes are read-only by default, so the tnsnames.ora file is in ORACLE_BASE_HOME/network/admin, instead of ORACLE_HOME/network/admin
- install.sh script:
- Address all ShellCheck warnings
- Remove unnecessary use of sudo (script runs as root)
- Ensure that permissions on setPassword.sh are set correctly
- Minor formatting fixes (trailing spaces, single vs. double quotes, etc.)
Tested with both VirtualBox and libvirt/KVM. Closes #380.
Signed-off-by: …
> Add OracleDatabase/21.3.0-XE project

- ContainerTools/README.md
- OracleLinux/9/.env
- OracleLinux/9/.gitattributes
- OracleLinux/9/.gitignore
- OracleLinux/9/README.md
- OracleLinux/9/Vagrantfile
- OracleLinux/9/scripts/container-tools.sh
- OracleLinux/9/scripts/install.sh
Adds an OracleLinux/9 project, based on the OracleLinux/8 project.
Changes from the OracleLinux/8 project:
- Updated the Oracle Linux version number wherever needed
- Added a comment to the `Vagrantfile` to note that the virtio nic type must be specified if adding network interfaces when using the VirtualBox provider
- Updated the `container-tools.sh` extension script to install the container-tools meta-package, rather than the container-tools module, since the module doesn't seem to be available yet
Also updated the `README.md` file for the ContainerTools project to state that the Container Tools functionality is available as an extension to both the OracleLinux/8 and OracleLinux/9 projects.
Closes #451.
Signed-off-by: Paul Neumann …
> Add OracleLinux/9 project

- boxes/oraclelinux/8-btrfs.json
- boxes/oraclelinux/8.json
Ready to be merged -- boxes are published on the public yum:
```
$ ~/src/olitt/olit-release-checks.sh  --version ol8 --cloud vagrant --provider virtualbox check-public
Running olit-release-checks.sh:
Clouds   : vagrant
Providers: virtualbox
Versions : ol8
Fetching latest versions
Checking uploads against https://yum.oracle.com/
OL8U7_x86_64-vagrant-btrfs-virtualbox-b412.box: OK -- Content-Length: 666235864
OL8U7_x86_64-vagrant-virtualbox-b411.box: OK -- Content-Length: 728631026
```
and match metadata in this PR:
```
~/src/olitt/olit-release-checks.sh  --version ol8 --cloud vagrant --provider virtualbox check-meta
Running olit-release-checks.sh:
Clouds   : vagrant
Providers: virtualbox
Versions : ol8
Fetching latest versions
Checking Vagrant metadata …
```
> build(metadata): ⬆ new OL8U7 release for vagrant-virtualbox

- OCNE/.env
- OCNE/README.md
- OCNE/Vagrantfile
- OCNE/scripts/provision.sh
Ref: issue #461
- Upgrade to OL8 [UEKR7](https://docs.oracle.com/en/operating-systems/olcne/1.5/relnotes/new.html#ocne-157)
- Change `Vagrantfile` `Virtualbox` `nic_type` to `virtio` drivers.
- Install `openssl` toolkit package.
- Change `conmon` from `/usr/libexec/crio/conmon` to `/usr/bin/conmon` in `/etc/crio/crio.conf` - as `conmon` in `@ol8_x86_64_appstream` now overrides `@ol8_x86_64_olcne15`
- Remove `firewall-cmd --add-masquerade` from provisioning script issue #460 .
Signed-off-by: Hussam Qasem <hqasem@tyeb.com>
> feat(ocne): Upgrade to OL8 UEKR7

- OracleDatabase/23.2.0-Free/.env
- OracleDatabase/23.2.0-Free/.gitattributes
- OracleDatabase/23.2.0-Free/.gitignore
- OracleDatabase/23.2.0-Free/README.md
- OracleDatabase/23.2.0-Free/Vagrantfile
- OracleDatabase/23.2.0-Free/ora-response/oracle-free-23c.conf.tmpl
- OracleDatabase/23.2.0-Free/scripts/install.sh
- OracleDatabase/23.2.0-Free/scripts/setPassword.sh
- OracleDatabase/23.2.0-Free/userscripts/.gitignore
- OracleDatabase/23.2.0-Free/userscripts/put_custom_scripts_here.txt
Adds an OracleDatabase/23.2.0-Free project, based on the OracleDatabase/21.3.0-XE project.
Notable changes from the 21.3.0-XE project:
- This release doesn't use a read-only Oracle home, so the `tnsnames.ora` file is under `/opt/oracle/product...`, rather than `/opt/oracle/homes...`
- This release doesn't include EM Express, so related code has been removed
Tested with both VirtualBox and libvirt/KVM. Closes #478.
Signed-off-by: Paul Neumann <[38871902+PaulNeumann@users.noreply.github.com](mailto:38871902+PaulNeumann@users.noreply.github.com)>
> Add OracleDatabase/23.2.0-Free project

- OCNE/.env
- OCNE/README.md
- OCNE/Vagrantfile
- OCNE/scripts/provision.sh
- Ocr-Yum-Mirror/README.md
- Ocr-Yum-Mirror/Vagrantfile
- Ocr-Yum-Mirror/scripts/install.sh
- Ocr-Yum-Mirror/scripts/ocr-mirror.sh
- Ocr-Yum-Mirror/scripts/yum-mirror.sh
* Calico as default pod networking
* Flannel is optional
* Multus is optional
* Helm (deprecated) is optional
* Gluster marked as (deprecated)
* User `--control-plane-nodes ` instead of deprecated `--master-nodes`
> feat(ocne): Upgrade to OCNE 1.6

- boxes/oraclelinux/8-btrfs.json
- boxes/oraclelinux/8.json
- boxes/oraclelinux/9-btrfs.json
- boxes/oraclelinux/9.json
Metadata for the OL8U9 and OL9U2 boxes.
Verified against source metadata:
```text
Running olit-release-checks.sh:
Clouds   : vagrant
Providers: virtualbox libvirt
Versions : ol8 ol9
Fetching latest versions
Checking Vagrant metadata
/boxes/oraclelinux/ol9/OL9U2_x86_64-vagrant-virtualbox-b481.box: OK
/boxes/oraclelinux/ol8/OL8U8_x86_64-vagrant-btrfs-libvirt-b488.box: OK
/boxes/oraclelinux/ol9/OL9U2_x86_64-vagrant-btrfs-virtualbox-b482.box: OK
/boxes/oraclelinux/ol9/OL9U2_x86_64-vagrant-libvirt-b483.box: OK
/boxes/oraclelinux/ol8/OL8U8_x86_64-vagrant-btrfs-virtualbox-b486.box: OK
/boxes/oraclelinux/ol8/OL8U8_x86_64-vagrant-virtualbox-b485.box: OK
/boxes/oraclelinux/ol9/OL9U2_x86_64-vagrant-btrfs-libvirt-b484.box: OK
/boxes/oraclelinux/ol8/OL8U8_x86_64-vagrant-libvirt-b487.box: OK
```
-- …
> build(metadata): :arrow_up: OL8U9 and OL9U2 release

- OracleDatabase/23.4.0-Free/.env
- OracleDatabase/23.4.0-Free/.gitattributes
- OracleDatabase/23.4.0-Free/.gitignore
- OracleDatabase/23.4.0-Free/README.md
- OracleDatabase/23.4.0-Free/Vagrantfile
- OracleDatabase/23.4.0-Free/ora-response/oracle-free-23ai.conf.tmpl
- OracleDatabase/23.4.0-Free/scripts/install.sh
- OracleDatabase/23.4.0-Free/scripts/setPassword.sh
- OracleDatabase/23.4.0-Free/userscripts/.gitignore
- OracleDatabase/23.4.0-Free/userscripts/put_custom_scripts_here.txt
Adds an Oracle Database 23ai Free project, based on the OracleDatabase/23.3.0-Free project. Since the 23.3.0-Free rpm is still available for download, this is a new project, rather than an update to the 23.3.0-Free project.
Notable changes from the 23.3.0-Free project:
- Use Oracle Linux 9 instead of Oracle Linux 8
- Add notes to `.env`, `README.md` and `Vagrantfile` stating that database creation will fail if the password includes special characters
- Modify `install.sh` to prevent auto-generated passwords from containing equals signs
Tested with both VirtualBox and libvirt/KVM.
Closes #505.
> Add OracleDatabase/23.4.0-Free project

- OracleDatabase/23.4.0-Free/scripts/install.sh
For the Oracle Database 23ai Free project, change the method used by `install.sh` to auto-generate passwords from `openssl rand -base64` to `openssl rand -hex`. This prevents including special characters in the generated password that would cause database creation to fail.
(Also, change the `openssl rand` "num" parameter from 9 to 8, to be consistent with the other single-instance database projects in this repository.)
Fixes #515
> Oracle DB 23ai Free - Prevent special chars in generated passwords

- OCNE/README.md
- OCNE/scripts/provision.sh
Changed provision.sh script to install ocne19 release and added a note to Readme that the project is not updated yet to latest OCNE 2.0 release.
> OCNE updated to latest OCNE v1 (ocne19) release

- OracleDG/OL7/scripts/07_setup_OracleNet.sh
- OracleDG/OL8/scripts/07_setup_OracleNet.sh
- OracleDG/OL9/scripts/07_setup_OracleNet.sh
DB_HOME vs ORACLE_HOME on listener setup
> minor fix on listener setup

- OracleDatabase/12.1.0.2/scripts/setPassword.sh
- OracleDatabase/12.2.0.1/scripts/setPassword.sh
- OracleDatabase/18.3.0/scripts/setPassword.sh
- OracleDatabase/18.4.0-XE/scripts/setPassword.sh
- OracleDatabase/19.3.0/scripts/setPassword.sh
- OracleDatabase/21.3.0-XE/scripts/setPassword.sh
- OracleDatabase/21.3.0/scripts/setPassword.sh
- OracleDatabase/23ai-Free/scripts/setPassword.sh
Modify the `setPassword.sh` script for all single-instance database projects (except 11g XE) to correctly set the PDBADMIN password when one or more PDBs have been added.
The updated script is identical for all 8 affected projects. Instead of parsing the directory names under `$ORACLE_BASE/oradata/$ORACLE_SID` to find the name of the PDB (which doesn't work when there are multiple PDBs), it queries `v$pdbs` and creates a PL/SQL script that sets the PDBADMIN password in all open PDBs.
Tested with both VirtualBox and libvirt providers.
Fixes #295
> Modify setPassword.sh to work with multiple PDBs
