OracleDatabase/README.md

Fix typo in database readme

---

OracleDatabase/README.md

new line missing

---

OracleDatabase/12.2.0.1/scripts/install.sh

Fix for #8 - Listener not on 1521

---

Kubernetes/.gitignore
Kubernetes/README.md
Kubernetes/Vagrantfile
Kubernetes/scripts/kubeadm-setup-master.sh
Kubernetes/scripts/kubeadm-setup-worker.sh
Kubernetes/scripts/provision.sh

Vagrant file for Kubernetes cluster.
Tested with Oracle Container Services 1.1.9 for use with Kubernetes (Kubernetes 1.9)

Kubernetes: initial upload

---

OracleLinux/preview/README.md

Fixed path for OL 7.5 preview into the README

Fixed Readme with correct cd to the path

---

DockerEngine/README.md
Kubernetes/LICENSE

LICENSE file was missing for Kubernetes Box

Added LICENSE file to Kubernetes

---

DockerEngine/LICENSE

LICENSE file was missing also for DockerEngine Box

Added LICENSE file to DockerEngine Box

---

Kubernetes/scripts/provision.sh

In some circumstances kubelet uses the _wrong_ IP address -- see kubernetes/kubernetes#61170
This commit ensures kubelet always uses the _right_ IP.

Kubernetes: set IP address to be used by kubelet

---

LAMP/LICENSE
LAMP/README.md
LAMP/Vagrantfile
LAMP/scripts/install.sh
LAMP/scripts/lamp.sh

Added LAMP ready-to-run vagrant box.
Based on latest OL7.x with Apache 2.4 and PHP 7.1 coming from Software Collections and MySQL Community 5.7.
Apache port 80 is redirected to port 8080 on the host.

LAMP - Software Collections

---

OracleLinux/preview/LICENSE
OracleLinux/preview/README.md
OracleLinux/preview/Vagrantfile
OracleLinux/preview/scripts/install.sh

re-added preview for OL.
This preview only address UEK5 and preview packages for OL because actually OL 7.5 is GA.

added UEK5 preview for OL7

---

OracleLinux/6/scripts/install.sh

Fix known issue on corrupted dracut configuration

Fixed /etc/dracut.conf.d/01-dracut-vm.conf issue

---

OracleDatabase/12.2.0.1/scripts/install.sh

Fix for bug #47

---

Kubernetes/scripts/provision.sh

Configuration change for compatibility with K8s 1.11 which has been posted in the Developer channel.

Update for K8s 1.11 from Developer channel

---

CODEOWNERS
OracleDG/.gitattributes
OracleDG/.gitignore
OracleDG/README.md
OracleDG/config/.gitignore
OracleDG/scripts/01_install_os_packages.sh
OracleDG/userscripts/.gitignore
OracleDG/userscripts/put_custom_scripts_here.txt
OracleRAC/.gitattributes
OracleRAC/README.md
OracleRAC/config/.gitignore
OracleRAC/scripts/.gitignore
OracleRAC/scripts/02_install_os_packages.sh
OracleRAC/userscripts/.gitignore
OracleRAC/userscripts/put_custom_scripts_here.txt

Rcitton 105

---

OracleDatabase/11.2.0.2/README.md
OracleDatabase/11.2.0.2/Vagrantfile
OracleDatabase/12.1.0.2/README.md
OracleDatabase/12.1.0.2/Vagrantfile
OracleDatabase/12.2.0.1/README.md
OracleDatabase/12.2.0.1/Vagrantfile
OracleDatabase/18.3.0/README.md
OracleDatabase/18.3.0/Vagrantfile
OracleDatabase/18.4.0-XE/README.md
OracleDatabase/18.4.0-XE/Vagrantfile

Include proxy plugin

---

OracleDatabase/19.3.0/.gitattributes
OracleDatabase/19.3.0/README.md
OracleDatabase/19.3.0/Vagrantfile
OracleDatabase/19.3.0/ora-response/db_install.rsp.tmpl
OracleDatabase/19.3.0/ora-response/dbca.rsp.tmpl
OracleDatabase/19.3.0/scripts/install.sh
OracleDatabase/19.3.0/scripts/oracle-rdbms.service
OracleDatabase/19.3.0/scripts/setPassword.sh
OracleDatabase/19.3.0/userscripts/.gitignore
OracleDatabase/19.3.0/userscripts/put_custom_scripts_here.txt

Introduce Oracle DB 19c scripts

---

OracleDatabase/12.1.0.2/scripts/install.sh
OracleDatabase/12.2.0.1/scripts/install.sh
OracleDatabase/18.3.0/scripts/install.sh

Enable EM global port

---

OracleAPEX/README.md
OracleAPEX/scripts/ords.sh

modified "ords.sh" script to get the same able to manage more ords releases.
Updated README.md file to remove release mentioning for APEX and ORDS

Introduce the support for ORDS 19.1

---

DockerEngine/Vagrantfile
DockerEngine/scripts/install.sh

DockerEngine: add support for vagrant-proxyconf plugin

---

Kubernetes/scripts/provision.sh

Prevents warning at install time

K8s: Add prerequisites

---

OracleDatabase/11.2.0.2/scripts/install.sh
OracleDatabase/12.1.0.2/scripts/install.sh
OracleDatabase/12.2.0.1/scripts/install.sh

Hey @PaulNeumann, I added the changes and they work fine on my Mac.
Do you mind to verify the builds on your Windows machine as well, please?

Unzip inside VM to avoid Windows FS sync issue #128

---

OLCNE/.env
OLCNE/.gitattributes
OLCNE/.gitignore
OLCNE/CONTRIBUTING.md
OLCNE/LICENSE
OLCNE/README.md
OLCNE/THIRD_PARTY_LICENSES.txt
OLCNE/Vagrantfile
OLCNE/scripts/provision.sh

New vagrant box for Oracle Linux Cloud Native Environment

---

OLCNE/scripts/provision.sh

OLCNE: add kubectl alias and completion.

---

OracleDatabase/11.2.0.2/scripts/install.sh
OracleDatabase/12.1.0.2/scripts/install.sh
OracleDatabase/12.2.0.1/scripts/install.sh
OracleDatabase/18.3.0/scripts/install.sh
OracleDatabase/18.4.0-XE/scripts/install.sh
OracleDatabase/19.3.0/scripts/install.sh

Abort install on any error

---

OracleLinux/8/LICENSE
OracleLinux/8/README.md
OracleLinux/8/Vagrantfile
OracleLinux/8/scripts/install.sh

Introducing OL8 box

---

Kubernetes/README.md
Kubernetes/scripts/provision.sh

Fixes #193 
Also adds a deprecation notice for the Kubernetes Vagrantfile.

Kubernetes: address compatibility issue with docker 19.03

---

OLCNE/scripts/provision.sh

Support for latest OLCNE release

Update for OLCNE 1.0.1

---

OracleDatabase/18.4.0-XE/README.md
OracleDatabase/18.4.0-XE/scripts/install.sh

No click-through XE

---

ContainerRegistry/Vagrantfile
DockerEngine/Vagrantfile
Kubernetes/Vagrantfile
LAMP/Vagrantfile
LAMP/scripts/lamp.sh
OLCNE/Vagrantfile
OracleAPEX/Vagrantfile
OracleDG/README.md
OracleDG/config/vagrant.yml
OracleDatabase/11.2.0.2/Vagrantfile
OracleDatabase/12.1.0.2/Vagrantfile
OracleDatabase/12.2.0.1/Vagrantfile
OracleDatabase/18.3.0/Vagrantfile
OracleDatabase/18.4.0-XE/Vagrantfile
OracleDatabase/19.3.0/Vagrantfile
OracleFPP/README.md
OracleLinux/6/Vagrantfile
OracleLinux/7/Vagrantfile
OracleLinux/8/Vagrantfile
OracleRAC/README.md
OracleRAC/config/vagrant.yml

- Update all references of `ol?-latest` to `oraclelinux/?`
- Update the box URL to the `json` file with the metadata

Addopt new box naming scheme.

---

OLCNE/.env
OLCNE/README.md
OLCNE/Vagrantfile
OLCNE/scripts/provision.sh

This should resolve any weirdness with adding new modules manually as well.
This should fix #225, #226 and #227.

Switch to using a single registry value for all images.

---

boxes/oraclelinux/6.json
boxes/oraclelinux/7.json
boxes/oraclelinux/8.json

Metadata for the latest boxes.
Merge only when boxes are published!

Boxes refresh, including first release for libvirt provider

---

boxes/oraclelinux/6.json
boxes/oraclelinux/7.json
boxes/oraclelinux/8.json

Improvement to the libvirt boxes.

New libvirt release

---

OracleLinux/8/Vagrantfile
OracleLinux/8/scripts/install.sh

Leave the choice to the user
Signed-off-by: Philippe Vanhaesendonck
<philippe.vanhaesendonck@oracle.com>

Don't install plugins during provisioning

---

OracleAPEX/README.md

Update the ORDS download URL in the APEX box `README.md` file to point to the current version download page. Fixes #234.

APEX box - update ORDS download URL

---

ContainerRegistry/README.md
DockerEngine/README.md
Kubernetes/README.md
LAMP/README.md
LAMP/Vagrantfile
LAMP/scripts/install.sh
OLCNE/README.md
OracleLinux/6/README.md
OracleLinux/6/Vagrantfile
OracleLinux/6/scripts/install.sh
OracleLinux/7/README.md
OracleLinux/7/Vagrantfile
OracleLinux/7/scripts/install.sh
OracleLinux/8/README.md

Signed-off-by: Philippe Vanhaesendonck
<philippe.vanhaesendonck@oracle.com>

Don't install plugins in Vagrantfiles

---

ContainerRegistry/README.md
README.md

- Update README.md at top level and in ContainerRegistry directory to reflect new repo name: vagrant-projects.
- Add libvirt/kvm instructions to top level README.md prerequisites
- refer to top level prerequisites in ContainerRegistry/README.md

Update README.md with new repo name

---

ContainerRegistry/Vagrantfile
DockerEngine/Vagrantfile
Kubernetes/Vagrantfile
LAMP/Vagrantfile
OLCNE/Vagrantfile
OracleAPEX/Vagrantfile
OracleDG/Vagrantfile
OracleDatabase/11.2.0.2/Vagrantfile
OracleDatabase/12.1.0.2/Vagrantfile
OracleDatabase/12.2.0.1/Vagrantfile
OracleDatabase/18.3.0/Vagrantfile
OracleDatabase/18.4.0-XE/Vagrantfile
OracleDatabase/19.3.0/Vagrantfile
OracleLinux/6/Vagrantfile
OracleLinux/7/Vagrantfile
OracleLinux/8/Vagrantfile
OracleRAC/Vagrantfile

This resolves #261 due to the URL change to the repo.

Updating base box URLs to renamed GH pages path.

---

README.md

Document metadata issue after renaming repository.

---

OLCNE/README.md

Update to README.md for change in repository name since the repository is named vagrant-projects now.

Update to README.md for change in repository name

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue-report.md

Issue template to capture user environment

Add an Issue template

---

ContainerRegistry/README.md
DockerEngine/README.md
Kubernetes/README.md
LAMP/README.md
OLCNE/README.md
OracleAPEX/README.md
OracleDG/README.md
OracleFPP/README.md
OracleLinux/6/README.md
OracleLinux/8/README.md
OracleLinux/README.md
OracleRAC/README.md

- Update README files to reflect new repo name (except for the projects having a running PR #265, #270)
- Basic markdown linting
--

Housekeeping

---

OracleLinux/7/scripts/container-runtime.sh

Invoke docker-storage-config only when we have an extra disk available.
This script is currently invoked by the DockerEngine and the OracleLinux/7 projects.
With the latter there is no extra disk available.
We still want to keep the option of using an extra disk when available to feature the btrfs driver.
--

Container runtime: don't require extra storage.

---

OracleLinux/7/scripts/container-runtime.sh

Container runtime: stat /var/lib if docker dir doesn't exist yet

---

boxes/oraclelinux/7.json
boxes/oraclelinux/8.json

Update to UEKR5U4 for OL7.
Remove extra disk for OL7/8.

New box release.

---

boxes/oraclelinux/7.json
boxes/oraclelinux/8.json

Metadata for the new boxes.
--

New release for OL8U3 and update for OL7U9.

---

README.md

Add note to top-level `README.md` stating that the projects in this repository are unlikely to work correctly on Windows hosts with Hyper-V enabled.
Closes #285.

Windows/Hyper-V note in README.md (oracle#285)

---

CONTRIBUTING.md
README.md
SECURITY.md

- Update CONTRIBUTING.md with new OCA information
- Add SECURITY.md for information on how to flag security issues
- Update README.md with the above
Signed-off-by: Sergio Leunissen <sergio.leunissen@oracle.com>

Add SECURITY.md, update CONTRIBUTING.md, surface in README.md

---

README.md

Remove boilerplate left in by mistake
Signed-off-by: Sergio Leunissen <sergio.leunissen@oracle.com>

remove template boilerplate

---

boxes/oraclelinux/7-btrfs.json
boxes/oraclelinux/8-btrfs.json

style(metadata):  Shorten description for Btrfs boxes

---

OLCNE/scripts/provision.sh

Update for OLCNE 1.3.
Cluster comes up nicely:
```
master1: ===== Your Oracle Linux Cloud Native Environment is operational. =====
master1: NAME                 STATUS   ROLES                  AGE     VERSION
master1: master1.vagrant.vm   Ready    control-plane,master   8m57s   v1.20.6+1.el8
master1: worker1.vagrant.vm   Ready    <none>                 8m9s    v1.20.6+1.el8
master1: worker2.vagrant.vm   Ready    <none>                 8m25s   v1.20.6+1.el8
```
Nodes are using the correct interface:
```
[vagrant@master1 ~]$ k get nodes -o wide
NAME                 STATUS   ROLES                  AGE   VERSION         INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                  KERNEL-VERSION                    CONTAINER-RUNTIME
master1.vagrant.vm   Ready    control-plane,master   13m …
```

feat(olcne): OLCNE 1.3 update

---

boxes/oraclelinux/7-btrfs.json
boxes/oraclelinux/7.json
boxes/oraclelinux/8-btrfs.json
boxes/oraclelinux/8.json

Metadata for the September quarterly update

---

boxes/oraclelinux/7-btrfs.json
boxes/oraclelinux/7.json
boxes/oraclelinux/8-btrfs.json
boxes/oraclelinux/8.json

OL7U9 with UEK6U3.
OL8U5 with UEK6U3.

Metadata for the November update.

---

boxes/oraclelinux/7-btrfs.json
boxes/oraclelinux/7.json
boxes/oraclelinux/8-btrfs.json
boxes/oraclelinux/8.json

OL7U9 with UEK6U3.
OL8U5 with UEK6U3.

Metadata for the February update.

---

OracleDG/scripts/07_setup_OracleNet.sh
OracleDG/scripts/standby_DB_setup.sh

Fix for  OracleDG - Switchover to standby fails #425

 OracleDG - Switchover to standby fails #425

---

boxes/oraclelinux/7-btrfs.json
boxes/oraclelinux/7.json
boxes/oraclelinux/8-btrfs.json
boxes/oraclelinux/8.json

build(metadata): OL8U6 release & OL7U9 refresh

---

ContainerTools/README.md
ContainerTools/Vagrantfile

- fix URL in Vagrantfile
- fix URL in README.md
Signed-off-by: Sergio Leunissen <sergio.leunissen@oracle.com>

fix outdated URLs

---

boxes/oraclelinux/8-btrfs.json
boxes/oraclelinux/8.json
boxes/oraclelinux/9-btrfs.json
boxes/oraclelinux/9.json

Metadata for new OL8/OL9 boxes

---

boxes/oraclelinux/8-btrfs.json
boxes/oraclelinux/8.json

build(metadata): :arrow_up: metadata for OL8U7 boxes

---

boxes/oraclelinux/9-btrfs.json
boxes/oraclelinux/9.json

build(metadata): :arrow_up: metadata for OL9U1 boxes

---

boxes/oraclelinux/8-btrfs.json
boxes/oraclelinux/8.json
boxes/oraclelinux/9-btrfs.json
boxes/oraclelinux/9.json

build(metadata): :arrow_up: new OL8U7 release for vagrant-virtualbox

---

boxes/oraclelinux/7-btrfs.json
boxes/oraclelinux/7.json
boxes/oraclelinux/8-btrfs.json
boxes/oraclelinux/8.json
boxes/oraclelinux/9-btrfs.json
boxes/oraclelinux/9.json

Metadata for the latest vagrant boxes
--

build(metadata): ⬆ OL8U9/OL9U3 release & OL7U9 refresh

---

OracleRAC/OL7/Vagrantfile
OracleRAC/OL7/config/vagrant.yml
OracleRAC/OL7/scripts/setup.sh
OracleRAC/OL8/Vagrantfile
OracleRAC/OL8/config/vagrant.yml
OracleRAC/OL8/scripts/setup.sh
OracleRAC/OL9/Vagrantfile
OracleRAC/OL9/config/vagrant.yml
OracleRAC/OL9/scripts/setup.sh

added sleep60 before "mount -t vboxsf vagrant /vagrant"

issue #519 & #520

---

boxes/oraclelinux/8-btrfs.json
boxes/oraclelinux/8.json
boxes/oraclelinux/9-btrfs.json
boxes/oraclelinux/9.json

Metadata update for latest OL8U10/OL9U4 boxes
--

build(metadata): :arrow_up: OL8U10/OL9U4 release

---

boxes/oraclelinux/8-btrfs.json
boxes/oraclelinux/8.json
boxes/oraclelinux/9-btrfs.json
boxes/oraclelinux/9.json

build(metadata): :arrow_up: OL8U10/OL9U4 update.

---

OracleRAC/OL7/scripts/05_setup_users.sh
OracleRAC/OL8/README.md
OracleRAC/OL8/Vagrantfile
OracleRAC/OL8/scripts/05_setup_users.sh
OracleRAC/OL8/scripts/setup.sh
OracleRAC/OL9/scripts/05_setup_users.sh

19c support for OL8 + minor fix for oracle/grid profile when ORestart is in use

+19c on OL8

---

boxes/oraclelinux/9-btrfs.json
boxes/oraclelinux/9.json

build(metadata): :arrow_up: OL9.5 release

---

boxes/oraclelinux/7-btrfs.json
boxes/oraclelinux/7.json
boxes/oraclelinux/8-aarch64.json
boxes/oraclelinux/8-btrfs.json
boxes/oraclelinux/8.json
boxes/oraclelinux/9-aarch64.json
boxes/oraclelinux/9-btrfs.json
boxes/oraclelinux/9.json

build: :arrow_up: aarch64 boxes + overall refresh
